feat: 방 생성 기능 구현
krafton-jungle-AI-InterviewMate/AI-InterviewMate-FE pull request #70
Opened 2023-02-18 13:56 UTC by KKamjangE

## Describe your changes
- POST API 연동
- 방 생성 유저면접, AI 면접으로 분리

## Issue number and link

- closes #5

2023-02-18 15:40 UTC, ahnanne requested changes
고생 많으셨습니다~ 코멘트 많긴 한데 거의 다 자잘한 부분들이라 크게 수정하실 부분은 없으실 거에요!
아 그리고 코멘트 남겨드린 부분 외에 한가지만 더 말씀 드릴 내용이 있습니다. :

`JoinError`랑 modal/room 쪽의 모달 모양 컴포넌트는 직접 구현하신 것 같은데 여유가 된다면 [MUI Dialog](https://mui.com/material-ui/react-dialog/)로 교체하면 좋을 것 같아요.
(참고로 보통 모달이라고 많이 하는데 정식 명칭은 모달이 아니라 다이얼로그라고 하네요.)

이런 다이얼로그 컴포넌트는 보통 웹 접근성이랑 사용성 등 고려할 부분이 많아서 직접 구현하기가 까다롭더라구요. 다이얼로그가 떴을 때 딤처리 된 배경은 스크롤이 되지 않는 게 좋고, 또 `JoinError` 같은 단순한 다이얼로그는 딤 영역을 클릭할 때도 닫히도록 처리해주는 게 사용성 측면에서 더 좋아보여요. (폼 다이얼로그의 경우에는 딤 영역을 실수로 클릭해서 작성 중인 내용이 날아가버리면 안 되니까 딤 영역 클릭해서 닫는 기능은 지금처럼 없는 게 맞는 것 같고요.)

저희 서비스에서 크리티컬한 사항은 아닌 듯하니 다음에 다른 프로젝트에서 다이얼로그 작업하실 때 참고하시면 좋을 것 같고, 이번에 작업하신 부분은 저도 여유가 된다면 리팩토링 해보도록 하겠습니다~

2023-02-18 15:40 UTC, ahnanne commented on src/components/modal/room/UserRoomForm.tsx
> +  passwordError: string | undefined;
보통은 이렇게 어떤 프로퍼티가 `undefined`일 수 있는 경우에는 optional property로 선언하는 편입니다.

```ts
interface StyledUserRoomFormProps {
  roomNameError?: string;
  passwordError?: string;
}
```

자바스크립트에서 `undefined`는 말 그대로 정의되지 않은 상태를 나타내기 위해 존재하는 타입이기 때문에 개발자가 임의로 쓸 일은 거의 없다고 보시면 돼요.
(참고: https://poiemaweb.com/js-data-type-variable#114-undefined)

2023-02-18 15:40 UTC, ahnanne commented on src/hooks/queries/lobby/lobby.ts
> +      refetchInterval: 3000,
오우 이렇게 3초마다 요청해도 괜찮다고 백엔드 쪽이랑 합의 보신 건가요!?

2023-02-18 15:40 UTC, ahnanne commented on src/pages/Lobby.tsx
> +import ServerError from "./ServerError";
이 `ServerError` 컴포넌트는 별도로 페이지로 사용되거나 라우팅 되고 있지 않아서 src/pages 보다는 src/components/common 정도로 위치를 변경하는 게 맞을 것 같아요

2023-02-18 15:40 UTC, ahnanne commented on src/pages/Lobby.tsx
> +    window.location.reload();
이렇게 직접 reload 해버리면 앱 전체를 다시 실행시키는 거라서, SPA 방식의 저희 앱과는 맞지 않는 것 같아요
`useGetInterviewRooms` 훅에서 다음과 같이 `refetch`도 꺼내서 사용하면 페이지 새로고침 없이 인터뷰 방 목록만 다시 받아올 수 있어요

```ts
// src/hooks/queries/lobby/lobby.ts

export const useGetInterviewRooms = () => {
  const { data, isSuccess, isLoading, isError, refetch } = useQuery(
    [ "fetchInterviewRooms" ],
    () => {
      return lobbyAPI.getInterviewRooms();
    },
    {
      refetchInterval: 3000,
    },
  );

  return {
    data,
    isSuccess,
    isLoading,
    isError,
    refetch,
  };
};
```

```ts
// src/pages/Lobby.tsx

const onClickReload = () => {
  refetch();
};
```

2023-02-18 15:40 UTC, ahnanne commented on src/pages/Lobby.tsx
>  function Lobby() {
화살표 함수로 수정 부탁 드려요

2023-02-18 15:40 UTC, ahnanne commented on src/components/modal/room/AiRoomForm.tsx
> +            <FormLabel>질문 개수</FormLabel>
저희 이거 라디오 버튼 말고 질문 개수 직접 입력하고 그 질문 개수 이내의 질문 꾸러미만 선택 가능하게 하는 방식으로 바꾸자고 얘기 했었던 걸로 기억하는데 백엔드분들께 확인해보셨나요??

그리고 이 부분을 비롯한 라디오 버튼 쓰는 부분은 `map` 써서 개선 부탁드립니다.
(https://ko.reactjs.org/docs/lists-and-keys.html#rendering-multiple-components)

2023-02-18 15:40 UTC, ahnanne commented on src/components/modal/room/AiRoomForm.tsx
> +}
여기도 `undefined`를 직접 사용하는 대신 optional property로 수정 부탁드려요

2023-02-18 15:40 UTC, ahnanne commented on src/components/modal/room/CreateRoom.tsx
> +function CreateRoom({ setModalCreateRoom }) {
화살표 함수로 수정해주세요

2023-02-18 15:40 UTC, ahnanne commented on src/components/modal/room/CreateRoom.tsx
> +  const [roomType, setRoomType] = useState("USER");
이렇게 하면 `roomType` type이 단순 `string`으로만 잡혀서,
```ts
useState<"AI" | "USER">("USER");
```
이런 식으로 범위를 좀 더 좁혀줘도 좋을 것 같습니다.

2023-02-19 06:50 UTC, KKamjangE commented on src/api/lobby/index.ts
> +import { PostInterviewRooms } from "api/lobby/type";
수정했습니다

2023-02-19 06:50 UTC, KKamjangE commented on package.json
> +    "@tanstack/react-query-devtools": "^4.24.6",
자동 업데이트 되나 확인만 하고 필요없어서 삭제했습니다

2023-02-19 06:52 UTC, KKamjangE commented on src/api/lobby/type.ts
> +export type PostInterviewRoomsPayloadData = {
이 부분은 이미 구현된 POST 요청보고 따라서 네이밍한건데 일단 알겠습니다

2023-02-19 06:55 UTC, ahnanne commented on src/api/lobby/type.ts
> +export type PostInterviewRoomsPayloadData = {
ㅋㅋㅋㅋㅋ네 그래서 예외 케이스고 생각난 김에 말씀 드렸다고 한 거에요 ㅎㅎ

2023-02-19 06:57 UTC, ahnanne commented on package.json
> +    "@tanstack/react-query-devtools": "^4.24.6",
그랬군요ㅎㅎ 그래도 개발할 때는 데브툴 계속 켜두면 좋으니까 메인 브랜치 머지되면 다시 붙여놓을게요~

2023-02-19 07:03 UTC, KKamjangE commented on src/api/lobby/type.ts
> +export type PostInterviewRoomsResponse = {
수정했습니다

2023-02-19 07:04 UTC, KKamjangE commented on src/components/lobby/JoinError.tsx
> +        <h2>해당 방에는 입장하실 수 없습니다.</h2>
수정했습니다

2023-02-19 07:06 UTC, KKamjangE commented on src/pages/Lobby.tsx
>  function Lobby() {
수정했습니다

2023-02-19 07:23 UTC, KKamjangE commented on src/components/lobby/Room.tsx
>  interface IRoom {
수정했습니다

2023-02-19 07:24 UTC, KKamjangE commented on src/components/lobby/Room.tsx
>      .warningComent {
수정했습니다

2023-02-19 07:25 UTC, KKamjangE commented on src/components/lobby/Room.tsx
>  function Room({
수정했습니다

2023-02-19 07:28 UTC, KKamjangE commented on src/components/lobby/Room.tsx
> +    <div style={{ marginBottom: 40 }}>
수정했습니다

2023-02-19 07:30 UTC, KKamjangE commented on src/components/lobby/Room.tsx
> +                <RiGitRepositoryPrivateFill size={"32px"} color={"var(--push-gray)"} />
수정했습니다

2023-02-19 07:30 UTC, KKamjangE commented on src/components/lobby/Room.tsx
> +                <MdPublic size={"32px"} color={"var(--push-gray)"} />
수정했습니다

2023-02-19 07:30 UTC, KKamjangE commented on src/components/modal/room/AiRoomForm.tsx
> +function AiRoomForm({ onClickModalClose, roomType }) {
수정했습니다

2023-02-19 07:31 UTC, KKamjangE commented on src/components/modal/room/AiRoomForm.tsx
> +  const feedback = useSetRecoilState(feedbackAtom);
수정했습니다

2023-02-19 07:31 UTC, KKamjangE commented on src/components/modal/room/UserRoomForm.tsx
> +  passwordError: string | undefined;
수정했습니다

2023-02-19 07:32 UTC, KKamjangE commented on src/hooks/queries/lobby/lobby.ts
> +      refetchInterval: 3000,
네

2023-02-19 07:33 UTC, KKamjangE commented on src/pages/Lobby.tsx
> +import ServerError from "./ServerError";
수정했습니다

2023-02-19 07:43 UTC, KKamjangE commented on src/pages/Lobby.tsx
> +    window.location.reload();
수정했습니다

2023-02-19 13:21 UTC, KKamjangE commented on src/components/modal/room/AiRoomForm.tsx
> +            <FormLabel>질문 개수</FormLabel>
수정했습니다

2023-02-19 13:22 UTC, KKamjangE commented on src/components/modal/room/AiRoomForm.tsx
> +}
수정했습니다

2023-02-19 13:22 UTC, KKamjangE commented on src/components/modal/room/CreateRoom.tsx
> +function CreateRoom({ setModalCreateRoom }) {
수정했습니다

2023-02-19 13:56 UTC, KKamjangE commented on src/components/modal/room/CreateRoom.tsx
> +  const [roomType, setRoomType] = useState("USER");
수정했습니다

2023-02-19 13:59 UTC, KKamjangE commented on src/hooks/queries/lobby/lobby.ts
> +      refetchInterval: 3000,
이 부분 목록 새로고침 있으니까 10초로 하자고 해서 10초로 변경했습니다

2023-02-19 14:03 UTC, ahnanne approved these changes
고생 많으셨어요! 더 수정하실 내용 없으시면 바로 머지하시면 될 것 같습니다.

2023-02-19 14:24 UTC, merged